# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a0df55a6ce29a16a8940ac2851eda1a88fcf858bbca83f59499b4969634cb307195e0bebf497dca82228050d253cdc4be8d9d33b196538877fe2084107624d3

test:
  secret_key_base: 492731b204f497e9de02e4a74ccc7e820114963433acfc516d2f80bf684bdfad44cfc0a87e769b0091a3620a912257d14e9de9de548395864e02424e201024bd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
